### ISSUE TITLE
consider allowing user to specify the extent to use for a superdoit_solo

### ISSUE THREAD

**Issue by LisaAlmarode** [dalehenrich/superDoit#39]
the superdoit_solo script is hardcoded to set GEM_SOLO_EXTENT to extent0.rowan.dbf. 
 
For general use, it would be nice if there was a mechanism to allow me to use a base extent0.dbf, or my own customized extent.

**Comment by dalehenrich** [comment]
Would an env var that defaulted to $GEMSTONE/bin/extent0.rowan.dbf work for you? ... I also assume that $GEMSTONE/bin/extent0.dbf should be expected to work, if one doesn't want to use a Rowan extent?

**Comment by LisaAlmarode** [comment]
I'd rather not depend on an environment variable; putting things in env vars tends to lead to madness if you go away and come back and have to sort out all the possible places it could be finding or holding onto references. BTDT.  It might work as a temporary workaround so we don't hold up anything now waiting for a more ideal solution, but I could also just create a copy of superdoit_solo and edit that.  

Since arguments to superdoit_solo are problematic, perhaps something could go into the topazini file to set the solo extent? I don't see why that wouldn't work, except that GEM_SOLO_EXTENT doesn't seem to have a runtime equivalent nor a topaz command. 

And yes, standard extent0.dbf should work (or a custom extent based on that, which I keep expecting to need).

**Comment by dalehenrich** [comment]
On a slightly different tack ... why do you care whether or not you are using a Rowan extentt for a .solo run?

**Comment by dalehenrich** [comment]
Wait, GEM_SOLO_EXTENT is a config item so you should be able to specify an alternate solo extent by doing `xxx.solo -- -C="GEM_SOLO_EXTENT=\<path-to-extent\>" ... and that ought to do the trick ...

**Comment by dalehenrich** [comment]
as of a recent commit in 3.6.4, Allen made changes to allow the last specification for a config def on the command line to take precedence (I think :))

**Comment by LisaAlmarode** [comment]
Doesn't seem like that will work, since it's after the --,  and topaz ignores anything on the command line after the first --. 
e.g, `$GEMSTONE/bin/topaz -l -C "GEM_SOLO_EXTENT=abc"  -- -C "GEM_SOLO_EXTENT=def"` results in GEMSTONE_SOLO_EXTENT of abc.

**Comment by dalehenrich** [comment]
Yes, but, superdoit passes all of the arguments after the first `--` it it's command line to topaz ... the following passes the `-T 10000` to topaz:
```
simple.solo -- -T 10000
````

**Comment by LisaAlmarode** [comment]
Ah... yes, I can run with this, and it must work since it proceeds to fail with a ROWAN unresolved symbol error...

```
unix > ./simple.solo -- -C "GEM_SOLO_EXTENT=$GEMSTONE/bin/extent0.dbf" 
GemStone Smalltalk Compiler Errors:
 Near line 25 of file [$GEMSTONE]/upgrade/projects/superDoit/gemstone/productTree/superdoit.tpz
   | resolvedProject |
   "install superDoit support code in image"
   resolvedProject := Rowan  
 *                    ^1                                              *******
 ```
 ...

**Comment by dalehenrich** [comment]
Perfect and that is a superDoit bug ... relative to being able to use extent0.dbf as solo extent ... and when I've done that... we should be good to go ...

I'm in the midst of the 3.6.3 to 3.6.4 upgrade extent0.rowan.dbf ... when I finish that work, I plan to merge my work into 3.6.4 and then proceed to address this and other issues as they pop up ...

**Comment by dalehenrich** [comment]
added battery tests to GemStone 3.6.4 to validate use of extent0.dbf for .solo scripts ... good to go ...
